<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ApplicationIcon Condition="Exists('Resources\app.ico')">Resources\app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Resources\**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
        <ProjectReference Include="..\PEIS.Report.Contracts\PEIS.Report.Contracts.csproj" />
    <ProjectReference Include="..\PEIS.Report.Docx.OpenXml\PEIS.Report.Docx.OpenXml.csproj" />
    <ProjectReference Include="..\PEIS.Report.Engine\PEIS.Report.Engine.csproj" />

    <ProjectReference Include="..\PEIS.Report.FastReport.OpenSource\PEIS.Report.FastReport.OpenSource.csproj" />
    <ProjectReference Include="..\PEIS.Report.Infrastructure.SqlServer\PEIS.Report.Infrastructure.SqlServer.csproj" />
  </ItemGroup>
</Project>
